name: "Release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version number
        required: true
        type: string

jobs:
  auto-publish:
    name: "AutoPublish"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
      - run: npm version ${{ github.event.inputs.version }} --no-commit-hooks --no-git-tag-version
      - run: npm install
      - run: npm run build
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
            commit_message: Bump version
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: docker release
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            jitsi/excalidraw-backend:${{ github.event.inputs.version }}
            jitsi/excalidraw-backend:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: release
        uses: softprops/action-gh-release@v2
        with:
            tag_name: ${{ github.event.inputs.version }}
            generate_release_notes: true
            make_latest: true
